### ISSUE TITLE
Incorrect nearest neighbor

### ISSUE THREAD

**Issue by elrnv** [Stoeoef/rstar#13] opened 2019-08-27 05:12 UTC
First off, thank you for your hard work on this crate.

I have run into a failure case on my machine when computing a `nearest_neighbor` for a query point against an rtree of a set of points (resembling a torus, so nothing crazy).

`nearest_neighbor` returns a different result for a tree built using `bulk_load` vs. a tree built using a sequence of `.insert` calls. More specifically, the result is correct for the `bulk_load`ed tree.

The test case is in this gist: https://gist.github.com/elrnv/9cedf04fdc11ab30e37118a47bb6e436

Unfortunately I couldn't prune the set of points much, but I hope this test helps in debugging :)

**Comment by Stoeoef** [comment] 2019-08-27 16:44
Thanks a lot for the report!
There seems indeed to be something fishy... no worries about the big set of input points, this already helps _a lot_ for debugging. I'm at it :)

**Comment by Stoeoef** [comment] 2019-08-27 17:09
In the meantime, using
`rtree.nearest_neighbor_iter(...).next()` seems to be a feasible workaround.
The problem lies within the `nearest_neighbor` method, which prunes more aggressively than the `nearest_neighbor_iter`. Seems like it is being too aggressive...
The bulk loaded tree is affected by this as well, although the likelihood is probably smaller in general.

**Comment by rmanoka** [comment] 2019-09-13 19:27
@Stoeoef  I was curious about this bug, and investigated the code a little bit.   Here is my understanding of the bug, and a possible fix.  The understanding may also be completely flawed, so please bear with me.  

As you've mentioned, the bug lies / is triggered by [this heuristic](https://github.com/Stoeoef/rstar/blob/master/rstar/src/algorithm/nearest_neighbor.rs#L148).  Here are the key observations:

1.  The heuristic tries to prune the search space in the special case where only a single nearest neighbor is requested.  This is done by maintaining an upper bound on the distance to the closest point, and ignoring points outside this threshold.  The requirement on this upper bound is that there is indeed a point within the envelopes already scanned which is not farther than the bound.

2.  For getting this upper bound, we are use `min_max_dist_2` of an `Envelope`.   However, when the dimensions is greater than 2, there is no guarantee that there is indeed a point inside the envelope that is within the distance returned by `min_max_dist_2`.   This is because, this function computes the closest corner, and then changes a single axis to the max. value possible in that axis, and takes the minimum among it.   In 3 or more dimensions, we could have an AABB, such that all the points that constructed the AABB are farther than this value.

If the above observations are correct, then we may be pruning out a different AABB based on this, which may actually contain the closest point.   One simple fix, as you have suggested is to not use this heuristic.   Another option is to compute `min_max_2` by first taking the farthest point, then changing one of the axis to the min point.   This ensures that the invariant the heuristic requires always holds.  However, I'm unsure where else this function is used, and thus if this is a valid fix.

Please let me know what you think, and sincere apologies if I'm my logic is flawed.

**Comment by Stoeoef** [comment] 2019-09-13 23:18
Thank you very much for looking into this!
Your observations sound quite right. This seems to be a bug in `min_max_2` for 3 dimensions and more, calculating an upper bound for point distance is after all the only purpose of this method. It just happened to work for 2 dimensions by coincidence. The method is not used anywhere else AFAIR.

Do you mind opening a PR for this? Setting only one component to the minimum value and leaving all others at the maximum value should be the right fix.

**Comment by Stoeoef** [comment] 2019-09-13 23:24
FYI: In case you are interested, this is the paper that introduces the `min_max` function:

http://www.postgis.org/support/nearestneighbor.pdf

**Comment by rmanoka** [comment] 2019-09-14 03:43
Nice paper;  their definition 4 also concurs that we should swap min-max in the current logic.
I've fixed `impl Envelope` of `AABB` in [my fork](https://github.com/rmanoka/rstar) and raised a PR.

Haven't added tests as the test-case OP provides is rather large.  @elrnv could you verify that the problem is fixed in the above fork?

**Comment by elrnv** [comment] 2019-09-14 04:59
@rmanoka The test I posted in the gist passes with your change.

**Closed** 2019-09-15 12:52 UTC

**Comment by Stoeoef** [comment] 2019-09-15 12:59
Version 0.5.1 is now available on crates.io and fixes this issue. Thanks to everyone involved.
